//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wed_learn_e.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bai_kiem_tra_dau_vao
    {
        public bai_kiem_tra_dau_vao()
        {
            this.cau_hoi_kiem_tra = new HashSet<cau_hoi_kiem_tra>();
            this.ket_qua_kiem_tra = new HashSet<ket_qua_kiem_tra>();
        }
    
        public int id_bai_kiem_tra { get; set; }
        public string tieu_de { get; set; }
        public string mo_ta { get; set; }
        public Nullable<int> nguoi_tao { get; set; }
    
        public virtual nguoi_dung nguoi_dung { get; set; }
        public virtual ICollection<cau_hoi_kiem_tra> cau_hoi_kiem_tra { get; set; }
        public virtual ICollection<ket_qua_kiem_tra> ket_qua_kiem_tra { get; set; }
    }
}
