//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wed_learn_e.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bai_luyen_viet
    {
        public bai_luyen_viet()
        {
            this.cau_hoi_luyen_viet = new HashSet<cau_hoi_luyen_viet>();
            this.lich_su_luyen_viet = new HashSet<lich_su_luyen_viet>();
        }
    
        public int id_bai_viet { get; set; }
        public Nullable<int> id_khoa_hoc { get; set; }
        public string tieu_de { get; set; }
        public string mo_ta { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
    
        public virtual khoa_hoc khoa_hoc { get; set; }
        public virtual ICollection<cau_hoi_luyen_viet> cau_hoi_luyen_viet { get; set; }
        public virtual ICollection<lich_su_luyen_viet> lich_su_luyen_viet { get; set; }
    }
}
