//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wed_learn_e.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bai_tap_thuc_hanh
    {
        public int id_bai_tap { get; set; }
        public Nullable<int> id_khoa_hoc { get; set; }
        public string tieu_de { get; set; }
        public string loai_bai_tap { get; set; }
        public string noi_dung_cau_hoi { get; set; }
        public string dap_an_mau { get; set; }
    
        public virtual khoa_hoc khoa_hoc { get; set; }
    }
}
