//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wed_learn_e.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bai_sap_xep
    {
        public bai_sap_xep()
        {
            this.cau_hoi_sap_xep = new HashSet<cau_hoi_sap_xep>();
            this.lich_su_sap_xep = new HashSet<lich_su_sap_xep>();
        }
    
        public int id_bai_sap_xep { get; set; }
        public Nullable<int> id_khoa_hoc { get; set; }
        public string tieu_de { get; set; }
        public string mo_ta { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
    
        public virtual khoa_hoc khoa_hoc { get; set; }
        public virtual ICollection<cau_hoi_sap_xep> cau_hoi_sap_xep { get; set; }
        public virtual ICollection<lich_su_sap_xep> lich_su_sap_xep { get; set; }
    }
}
