//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wed_learn_e.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bai_luyen_noi
    {
        public bai_luyen_noi()
        {
            this.lich_su_luyen_noi = new HashSet<lich_su_luyen_noi>();
        }
    
        public int id_bai_noi { get; set; }
        public Nullable<int> id_khoa_hoc { get; set; }
        public string loai_bai_noi { get; set; }
        public string noi_dung_goc { get; set; }
        public string nghia_tieng_viet { get; set; }
        public string phien_am { get; set; }
        public string file_am_thanh_mau { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
    
        public virtual khoa_hoc khoa_hoc { get; set; }
        public virtual ICollection<lich_su_luyen_noi> lich_su_luyen_noi { get; set; }
    }
}
