//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wed_learn_e.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bai_giang_video
    {
        public int id_video { get; set; }
        public Nullable<int> id_khoa_hoc { get; set; }
        public string tieu_de { get; set; }
        public string duong_dan_video { get; set; }
        public Nullable<int> thoi_luong_phut { get; set; }
    
        public virtual khoa_hoc khoa_hoc { get; set; }
    }
}
