//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wed_learn_e.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class binh_luan
    {
        public int id_binh_luan { get; set; }
        public int id_nguoi_dung { get; set; }
        public int id_cap_do { get; set; }
        public string noi_dung { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public Nullable<bool> trang_thai { get; set; }
        public string chu_de { get; set; }
    
        public virtual cap_do cap_do { get; set; }
        public virtual nguoi_dung nguoi_dung { get; set; }
    }
}
