//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wed_learn_e.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cap_do
    {
        public cap_do()
        {
            this.ket_qua_kiem_tra = new HashSet<ket_qua_kiem_tra>();
            this.khoa_hoc = new HashSet<khoa_hoc>();
            this.nguoi_dung = new HashSet<nguoi_dung>();
            this.binh_luan = new HashSet<binh_luan>();
        }
    
        public int id_cap_do { get; set; }
        public string ten_cap_do { get; set; }
        public string mo_ta { get; set; }
    
        public virtual ICollection<ket_qua_kiem_tra> ket_qua_kiem_tra { get; set; }
        public virtual ICollection<khoa_hoc> khoa_hoc { get; set; }
        public virtual ICollection<nguoi_dung> nguoi_dung { get; set; }
        public virtual ICollection<binh_luan> binh_luan { get; set; }
    }
}
