//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wed_learn_e.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cau_hoi_sap_xep
    {
        public int id_cau_hoi { get; set; }
        public Nullable<int> id_bai_sap_xep { get; set; }
        public string cau_tieng_viet { get; set; }
        public string dap_an_dung { get; set; }
    
        public virtual bai_sap_xep bai_sap_xep { get; set; }
    }
}
