//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wed_learn_e.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cau_hoi_luyen_nghe
    {
        public int id_cau_hoi { get; set; }
        public Nullable<int> id_bai_nghe { get; set; }
        public string noi_dung_cau_hoi { get; set; }
        public string dap_an_a { get; set; }
        public string dap_an_b { get; set; }
        public string dap_an_c { get; set; }
        public string dap_an_d { get; set; }
        public string dap_an_dung { get; set; }
    
        public virtual bai_luyen_nghe bai_luyen_nghe { get; set; }
    }
}
