//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wed_learn_e.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cau_hoi_kiem_tra
    {
        public int id_cau_hoi { get; set; }
        public Nullable<int> id_bai_kiem_tra { get; set; }
        public string noi_dung_cau_hoi { get; set; }
        public string dap_an_a { get; set; }
        public string dap_an_b { get; set; }
        public string dap_an_c { get; set; }
        public string dap_an_d { get; set; }
        public string dap_an_dung { get; set; }
        public Nullable<int> nguoi_tao { get; set; }
        public Nullable<int> nguoi_cap_nhat { get; set; }
        public Nullable<System.DateTime> ngay_cap_nhat { get; set; }
    
        public virtual bai_kiem_tra_dau_vao bai_kiem_tra_dau_vao { get; set; }
        public virtual nguoi_dung nguoi_dung { get; set; }
        public virtual nguoi_dung nguoi_dung1 { get; set; }
    }
}
