//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wed_learn_e.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class footer_cot
    {
        public int id { get; set; }
        public string tieu_de { get; set; }
        public string noi_dung_html { get; set; }
        public Nullable<int> thu_tu { get; set; }
    }
}
