//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wed_learn_e.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_kho_bau
    {
        public game_kho_bau()
        {
            this.cau_hoi_kho_bau = new HashSet<cau_hoi_kho_bau>();
        }
    
        public int id_game { get; set; }
        public Nullable<int> id_cap_do { get; set; }
        public string tieu_de { get; set; }
        public string tu_khoa_cuoi { get; set; }
        public string mo_ta { get; set; }
    
        public virtual ICollection<cau_hoi_kho_bau> cau_hoi_kho_bau { get; set; }
    }
}
