//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wed_learn_e.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ket_qua_kiem_tra
    {
        public int id_ket_qua { get; set; }
        public Nullable<int> id_nguoi_dung { get; set; }
        public Nullable<int> id_bai_kiem_tra { get; set; }
        public int diem_so { get; set; }
        public Nullable<int> id_cap_do_dat_duoc { get; set; }
        public Nullable<System.DateTime> ngay_lam_bai { get; set; }
    
        public virtual bai_kiem_tra_dau_vao bai_kiem_tra_dau_vao { get; set; }
        public virtual cap_do cap_do { get; set; }
        public virtual nguoi_dung nguoi_dung { get; set; }
    }
}
