//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wed_learn_e.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khoa_hoc
    {
        public khoa_hoc()
        {
            this.bai_giang_video = new HashSet<bai_giang_video>();
            this.bai_tap_thuc_hanh = new HashSet<bai_tap_thuc_hanh>();
            this.tien_do_hoc_tap = new HashSet<tien_do_hoc_tap>();
            this.tu_vung = new HashSet<tu_vung>();
            this.bai_luyen_noi = new HashSet<bai_luyen_noi>();
            this.bai_luyen_nghe = new HashSet<bai_luyen_nghe>();
            this.bai_luyen_viet = new HashSet<bai_luyen_viet>();
            this.bai_sap_xep = new HashSet<bai_sap_xep>();
        }
    
        public int id_khoa_hoc { get; set; }
        public Nullable<int> id_cap_do { get; set; }
        public string ten_khoa_hoc { get; set; }
        public string duong_dan_icon { get; set; }
        public string mo_ta { get; set; }
        public Nullable<bool> trang_thai_hoat_dong { get; set; }
        public Nullable<int> nguoi_tao { get; set; }
        public Nullable<int> nguoi_cap_nhat { get; set; }
        public Nullable<System.DateTime> ngay_cap_nhat { get; set; }
    
        public virtual ICollection<bai_giang_video> bai_giang_video { get; set; }
        public virtual ICollection<bai_tap_thuc_hanh> bai_tap_thuc_hanh { get; set; }
        public virtual cap_do cap_do { get; set; }
        public virtual nguoi_dung nguoi_dung { get; set; }
        public virtual nguoi_dung nguoi_dung1 { get; set; }
        public virtual ICollection<tien_do_hoc_tap> tien_do_hoc_tap { get; set; }
        public virtual ICollection<tu_vung> tu_vung { get; set; }
        public virtual ICollection<bai_luyen_noi> bai_luyen_noi { get; set; }
        public virtual ICollection<bai_luyen_nghe> bai_luyen_nghe { get; set; }
        public virtual ICollection<bai_luyen_viet> bai_luyen_viet { get; set; }
        public virtual ICollection<bai_sap_xep> bai_sap_xep { get; set; }
    }
}
