//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wed_learn_e.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lich_su_luyen_noi
    {
        public int id_lich_su { get; set; }
        public Nullable<int> id_nguoi_dung { get; set; }
        public Nullable<int> id_bai_noi { get; set; }
        public Nullable<System.DateTime> ngay_hoan_thanh { get; set; }
    
        public virtual bai_luyen_noi bai_luyen_noi { get; set; }
        public virtual nguoi_dung nguoi_dung { get; set; }
    }
}
