//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wed_learn_e.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wed_learn_eEntities : DbContext
    {
        public wed_learn_eEntities()
            : base("name=wed_learn_eEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bai_giang_video> bai_giang_video { get; set; }
        public DbSet<bai_kiem_tra_dau_vao> bai_kiem_tra_dau_vao { get; set; }
        public DbSet<bai_tap_thuc_hanh> bai_tap_thuc_hanh { get; set; }
        public DbSet<cap_do> cap_do { get; set; }
        public DbSet<cau_hoi_kiem_tra> cau_hoi_kiem_tra { get; set; }
        public DbSet<ket_qua_kiem_tra> ket_qua_kiem_tra { get; set; }
        public DbSet<khoa_hoc> khoa_hoc { get; set; }
        public DbSet<nguoi_dung> nguoi_dung { get; set; }
        public DbSet<nhat_ky_quan_tri> nhat_ky_quan_tri { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tien_do_hoc_tap> tien_do_hoc_tap { get; set; }
        public DbSet<tu_vung> tu_vung { get; set; }
        public DbSet<bai_luyen_noi> bai_luyen_noi { get; set; }
        public DbSet<bai_luyen_nghe> bai_luyen_nghe { get; set; }
        public DbSet<cau_hoi_luyen_nghe> cau_hoi_luyen_nghe { get; set; }
        public DbSet<bai_luyen_viet> bai_luyen_viet { get; set; }
        public DbSet<cau_hoi_luyen_viet> cau_hoi_luyen_viet { get; set; }
        public DbSet<lich_su_luyen_viet> lich_su_luyen_viet { get; set; }
        public DbSet<lich_su_luyen_nghe> lich_su_luyen_nghe { get; set; }
        public DbSet<lich_su_luyen_noi> lich_su_luyen_noi { get; set; }
        public DbSet<lich_su_video> lich_su_video { get; set; }
        public DbSet<bai_sap_xep> bai_sap_xep { get; set; }
        public DbSet<cau_hoi_sap_xep> cau_hoi_sap_xep { get; set; }
        public DbSet<lich_su_sap_xep> lich_su_sap_xep { get; set; }
        public DbSet<cau_hoi_kho_bau> cau_hoi_kho_bau { get; set; }
        public DbSet<game_kho_bau> game_kho_bau { get; set; }
        public DbSet<lich_su_kho_bau> lich_su_kho_bau { get; set; }
        public DbSet<binh_luan> binh_luan { get; set; }
        public DbSet<Vocabulary> Vocabularies { get; set; }
        public DbSet<Idiom> Idioms { get; set; }
        public DbSet<cau_hoi_video> cau_hoi_video { get; set; }
        public DbSet<ngu_phap> ngu_phap { get; set; }
        public DbSet<feature_trang_chu> feature_trang_chu { get; set; }
        public DbSet<footer_cot> footer_cot { get; set; }
        public DbSet<thong_tin_khoa_hoc> thong_tin_khoa_hoc { get; set; }
    }
}
