//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wed_learn_e.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ngu_phap
    {
        public int id_ngu_phap { get; set; }
        public Nullable<int> id_cap_do { get; set; }
        public string icon { get; set; }
        public string tieu_de { get; set; }
        public string mo_ta_ngan { get; set; }
        public string cong_thuc { get; set; }
        public string cach_dung { get; set; }
        public string vi_du { get; set; }
        public string luu_y_them { get; set; }
    }
}
