//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wed_learn_e.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nguoi_dung
    {
        public nguoi_dung()
        {
            this.bai_kiem_tra_dau_vao = new HashSet<bai_kiem_tra_dau_vao>();
            this.cau_hoi_kiem_tra = new HashSet<cau_hoi_kiem_tra>();
            this.cau_hoi_kiem_tra1 = new HashSet<cau_hoi_kiem_tra>();
            this.ket_qua_kiem_tra = new HashSet<ket_qua_kiem_tra>();
            this.khoa_hoc = new HashSet<khoa_hoc>();
            this.khoa_hoc1 = new HashSet<khoa_hoc>();
            this.nhat_ky_quan_tri = new HashSet<nhat_ky_quan_tri>();
            this.tien_do_hoc_tap = new HashSet<tien_do_hoc_tap>();
            this.lich_su_luyen_viet = new HashSet<lich_su_luyen_viet>();
            this.lich_su_luyen_nghe = new HashSet<lich_su_luyen_nghe>();
            this.lich_su_luyen_noi = new HashSet<lich_su_luyen_noi>();
            this.lich_su_video = new HashSet<lich_su_video>();
            this.lich_su_sap_xep = new HashSet<lich_su_sap_xep>();
        }
    
        public int id_nguoi_dung { get; set; }
        public string ten_dang_nhap { get; set; }
        public string mat_khau { get; set; }
        public string ho_va_ten { get; set; }
        public string email { get; set; }
        public string vai_tro { get; set; }
        public Nullable<int> id_cap_do_hien_tai { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public string MatKhauNL { get; set; }
        public Nullable<int> loai_tai_khoan { get; set; }
        public Nullable<int> so_luong_khoa_hoc { get; set; }
    
        public virtual ICollection<bai_kiem_tra_dau_vao> bai_kiem_tra_dau_vao { get; set; }
        public virtual cap_do cap_do { get; set; }
        public virtual ICollection<cau_hoi_kiem_tra> cau_hoi_kiem_tra { get; set; }
        public virtual ICollection<cau_hoi_kiem_tra> cau_hoi_kiem_tra1 { get; set; }
        public virtual ICollection<ket_qua_kiem_tra> ket_qua_kiem_tra { get; set; }
        public virtual ICollection<khoa_hoc> khoa_hoc { get; set; }
        public virtual ICollection<khoa_hoc> khoa_hoc1 { get; set; }
        public virtual ICollection<nhat_ky_quan_tri> nhat_ky_quan_tri { get; set; }
        public virtual ICollection<tien_do_hoc_tap> tien_do_hoc_tap { get; set; }
        public virtual ICollection<lich_su_luyen_viet> lich_su_luyen_viet { get; set; }
        public virtual ICollection<lich_su_luyen_nghe> lich_su_luyen_nghe { get; set; }
        public virtual ICollection<lich_su_luyen_noi> lich_su_luyen_noi { get; set; }
        public virtual ICollection<lich_su_video> lich_su_video { get; set; }
        public virtual ICollection<lich_su_sap_xep> lich_su_sap_xep { get; set; }
    }
}
