//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wed_learn_e.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhat_ky_quan_tri
    {
        public int id_nhat_ky { get; set; }
        public int id_admin { get; set; }
        public string hanh_dong { get; set; }
        public string ten_bang_tac_dong { get; set; }
        public Nullable<int> id_ban_ghi_tac_dong { get; set; }
        public string chi_tiet_cu { get; set; }
        public string chi_tiet_moi { get; set; }
        public Nullable<System.DateTime> ngay_thuc_hien { get; set; }
    
        public virtual nguoi_dung nguoi_dung { get; set; }
    }
}
