//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wed_learn_e.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thong_tin_khoa_hoc
    {
        public int id { get; set; }
        public Nullable<int> id_khoa_hoc { get; set; }
        public string noi_dung_html { get; set; }
    
        public virtual khoa_hoc khoa_hoc { get; set; }
    }
}
