//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wed_learn_e.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tu_vung
    {
        public int id_tu_vung { get; set; }
        public Nullable<int> id_khoa_hoc { get; set; }
        public string tu_tieng_anh { get; set; }
        public string loai_tu { get; set; }
        public string nghia_tieng_viet { get; set; }
        public string phien_am { get; set; }
        public string vi_du { get; set; }
    
        public virtual khoa_hoc khoa_hoc { get; set; }
    }
}
